### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna hämta flera produkter

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#11]
**Tasks:**

- [ ] Skapa API-endpoint för att hämta en lista av alla produkter
- [ ] Implementera filtrering 
- [ ] Implementera logik för att hämta produkterna från databasen
- [ ] Skriv enhetstester för att verifiera hämtningen av flera produkter

**Definition of done:**
- [ ] Administratören ska kunna hämta flera produkter beroende på sorterings val.  
- [ ] Administratören ska kunna använda filtrering för att hämta en lista av produkter baserat på kategori, produktgrupp, prisintervall, lagerstatus eller andra kriterier.
- [ ] Paginering ska kunna användas för att returnera ett specifikt antal produkter per sida och möjliggöra navigering mellan sidorna.
- [ ] Systemet ska validera om produkter existerar i databasen och returnera dessa.
