### ISSUE TITLE
Api-Products: Som en kund vill jag kunna hämta flera produkter via kategori samt filter

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#12]
**Tasks:**

- [x] Skapa API-endpoint för att hämta en lista av alla produkter via kategori id
- [x] Implementera logik för att hämta produkterna från databasen
- [x] Skriv enhetstester för att verifiera hämtningen av flera produkter
- [x] Implementera felhantering för ogiltig kategori eller om inga produkter finns
- [x]  Lägg till paginering och sorteringsmöjligheter exempelvis pris

Definition of done:

- [x] Kunden ska kunna hämta flera produkter beroende på sorterings val.  
- [x] Kunden ska kunna använda filtrering för att hämta en lista av produkter baserat på kategori, prisintervall, eller andra kriterier.
- [x] Paginering ska kunna användas för att returnera ett specifikt antal produkter per sida och möjliggöra navigering mellan sidorna.
- [x] Systemet ska validera om produkter existerar i databasen och returnera dessa.
- [x]  Systemet skickar tillbaka en tom lista ifall ingen produkt/kategori finns med angivet namn.

**Comment by zoturen** [comment]
![Image](https://github.com/user-attachments/assets/767c315e-4f26-4ac6-8225-64fa3cf06768)
