### ISSUE TITLE
Api-Products: Som en kund vill jag kunna hämta flera kategorier

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#15]
**Tasks:** 

- [x] Skapa API-endpoint för att hämta en lista över alla kategorier
- [x] Implementera logik för att hämta alla kategorier från databasen
- [x] Skriv enhetstester för att verifiera hämtningen av alla kategorier

Definition of done:
- [x] Kunden ska kunna hämta en lista med alla kategorier.
