### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna skapa en produktgrupp

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#18]
**Tasks:**
- [ ] Skapa API-endpoint för att skapa en produktgrupp
- [ ] Validera indata för produktgruppen (namn, beskrivning)
- [ ] Implementera logik för att spara produktgruppen in i databasen
- [ ] Skapa kopplingar till de relaterade entiteterna, som Category
- [ ] Skriv enhetstester för att verifiera produktgruppens skapande
- [ ] Implementera felhantering (t.ex. ogiltiga fält eller saknade relationer)

**Definition of done:**
-  [ ] Administratören ska kunna skapa en produktgrupp med namn och beskrivning 
- [ ] Produktgruppen ska valideras och skickas iväg till den kopplade databasen och ska alltid returnera en statuskod tillbaka beroende på resultatet.
