### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna hämta flera produktgrupper

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#20]
**Tasks:**
- [ ] Skapa API-endpoint för att hämta en lista över alla produktgrupper
- [ ] Implementera logik för att hämta alla produktgrupper från databasen
- [ ] Skriv enhetstester för att verifiera hämtningen av alla produktgrupper

**Definition of done:**
- [ ] Administratören ska kunna hämta alla produktgrupper utan relationer. (för att exempelvis redigera en).
