### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna redigera en produktgrupp

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#21]
**Tasks:**

- [ ] Skapa API-endpoint för att uppdatera en produktgrupp baserat på dess ProductgroupId
- [ ] Validera indata för redigering (t.ex. om produktgruppen existerar och om fält är giltiga)
- [ ] Implementera logik för att uppdatera produktgruppen fält i databasen
- [ ] Hantera uppdateringar av relationer, såsom pris, variationer eller kategori

**Definition of done:**
- [ ] Administratören ska kunna redigera en produktgrupp genom att ange produktgruppens ID och de fält som ska uppdateras, som till exempel namn, beskrivning.
- [ ] Systemet ska validera om produktgruppen med det angivna ID:et existerar i databasen och så att alla obligatoriska fält är ifyllda. API:et ska alltid returnera en statuskod beroende på resultatet.
-  [ ] Om valideringen lyckas, ska systemet uppdatera fälten som är redigerade.
