### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna ta bort en produktgrupp

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#22]
**Tasks:**

- [ ] Skapa API-endpoint för att ta bort en produktgrupp baserat på dess ProductgroupID
- [ ] Validera att produktgruppen existerar innan borttagning
- [ ] Implementera logik för att radera produktgruppen från databasen
- [ ] Implementera relationshantering (t.ex. hantera kopplade Categories)
- [ ] Skriv enhetstester för borttagning av produktgruppen
- [ ] Implementera felmeddelanden vid ogiltiga borttagningsförsök

**Definition of done:**
- [ ] Administratören ska kunna ta bort en produktgrupp (genom att ange produktgruppens ID), med tillhörande fält, som till exempel namn, beskrivning samt de tillhörande relationerna.
- [ ] Systemet ska validera om produktgruppen med det angivna ID:et existerar i databasen och försöka radera produktgruppen. Beroende på resultat ska API:et alltid returnera en statuskod tillbaka.
