### ISSUE TITLE
Api: Products

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#23]
- [ ] EC-rika-project/API-Products-RIKA-WIN23#3
- [ ] EC-rika-project/API-Products-RIKA-WIN23#4
- [ ] EC-rika-project/API-Products-RIKA-WIN23#5
- [ ] EC-rika-project/API-Products-RIKA-WIN23#9
- [ ] EC-rika-project/API-Products-RIKA-WIN23#10
- [ ] EC-rika-project/API-Products-RIKA-WIN23#11
- [ ] EC-rika-project/API-Products-RIKA-WIN23#12
- [ ] EC-rika-project/API-Products-RIKA-WIN23#6
- [ ] EC-rika-project/API-Products-RIKA-WIN23#7
- [ ] EC-rika-project/API-Products-RIKA-WIN23#8
- [ ] EC-rika-project/API-Products-RIKA-WIN23#13

- [ ] EC-rika-project/API-Products-RIKA-WIN23#14
- [ ] EC-rika-project/API-Products-RIKA-WIN23#15
- [ ] EC-rika-project/API-Products-RIKA-WIN23#16
- [ ] EC-rika-project/API-Products-RIKA-WIN23#17
- [ ] EC-rika-project/API-Products-RIKA-WIN23#18
- [ ] EC-rika-project/API-Products-RIKA-WIN23#19
- [ ] EC-rika-project/API-Products-RIKA-WIN23#20
- [ ] EC-rika-project/API-Products-RIKA-WIN23#21
- [ ] EC-rika-project/API-Products-RIKA-WIN23#22
