### ISSUE TITLE
Uppsättning API: Products

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#24]
**Tasks:**
- [x]  Skapa GitHub-repo
- [x]  Sätt upp projekt inklusive mappstruktur
- [x] Skapa main branch
- [x] Skapa dev branch
