### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna lägga till en produkt

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#3]
**Tasks:**

- [ ] Skapa API-endpoint för att skapa en ny produkt
- [ ] Validera indata för produkten (namn, beskrivning, pris, kategori, etc.)
- [ ] Implementera logik för att spara produkten in i databasen
- [ ] Skapa kopplingar till de relaterade entiteterna, som ProductGroup, Category och ProductVariation
- [ ] Skriv enhetstester för att verifiera produktens skapande
- [ ] Implementera felhantering (t.ex. ogiltiga fält eller saknade relationer)

**Definition of done:**
- [ ] Administratören ska kunna skapa en produkt med namn, beskrivning, pris, kategori och produktgrupp.
- [ ] Produkten ska valideras och skickas iväg till den kopplade databasen och ska alltid returnera en statuskod tillbaka beroende på resultatet.
