### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna ta bort en produkt

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#4]
**Tasks:**

- [ ] Skapa API-endpoint för att ta bort en produkt baserat på dess ProductId
- [ ] Validera att produkten existerar innan borttagning
- [ ] Implementera logik för att radera produkten från databasen
- [ ] Implementera relationshantering (t.ex. hantera kopplade ProductVariations)
- [ ] Skriv enhetstester för borttagning av produkten
- [ ] Implementera felmeddelanden vid ogiltiga borttagningsförsök

**Definition of done:**
- [ ] Administratören ska kunna ta bort en produkt (genom att ange produktens ID), med tillhörande fält, som till exempel namn, beskrivning, pris, kategori, och produktgruppen. 
- [ ] Systemet ska validera om produkten med det angivna ID:et existerar i databasen och försöka radera produkten. Beroende på resultat ska API:et alltid returnera en statuskod tillbaka.
