### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna redigera en produkt

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#5]
**Tasks:**

- [ ] Skapa API-endpoint för att uppdatera en produkt baserat på dess ProductId
- [ ] Validera indata för redigering (t.ex. om produkten existerar och om fält är giltiga)
- [ ] Implementera logik för att uppdatera produktens fält i databasen
- [ ] Hantera uppdateringar av relationer, såsom pris, variationer eller kategori
- [ ] Skriv enhetstester för att verifiera redigeringen av produkten
- [ ] Implementera felhantering vid misslyckad uppdatering

Definition of done
- [ ] Administratören ska kunna redigera en produkt genom att ange produktens ID och de fält som ska uppdateras, som till exempel namn, beskrivning, pris, kategori eller produktgrupp.
- [ ] Systemet ska validera om produkten med det angivna ID:et existerar i databasen och så att alla obligatoriska fält är ifyllda. API:et ska alltid returnera en statuskod beroende på resultatet.
- [ ] Om valideringen lyckas, ska systemet uppdatera fälten som är redigerade.
