### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna skapa en kategori

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#6]
**Tasks:**

- [ ] Skapa API-endpoint för att skapa en ny kategori
- [ ] Validera indata för kategorin (namn, beskrivning)
- [ ] Implementera logik för att spara kategorin i databasen
- [ ] Skriv enhetstester för att verifiera kategorins skapande
- [ ] Implementera felhantering för redan existerande kategorier eller ogiltiga indata

**Definition of done:**
- [ ] Administratören ska kunna skapa en ny kategori.
- [ ] Systemet ska validera den nya kategorin och se till så att det inte redan existerar en med samma namn i databasen. Ska alltid returnera en statuskod beroende på resultatet.
