### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna ta bort en kategori

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#7]
**Tasks:**

- [ ] Skapa API-endpoint för att ta bort en kategori baserat på CategoryId
- [ ] Validera att kategorin existerar 
- [ ] Implementera logik för att radera kategorin från databasen
- [ ] Skriv enhetstester för borttagning av kategori
- [ ] Implementera felmeddelanden vid ogiltig borttagning (t.ex. beroenden till andra tabeller)

**Definition of done:**
- [ ] Administratören ska kunna ta bort en kategori (genom att ange kategorins ID), med tillhörande fält. Med alternativ som att endast ta bort kategorin, eller även ta bort tillhörande kopplingar (produktgrupp och produkter).
- [ ] Systemet ska validera om kategorin med det angivna ID:et existerar i databasen och försöka radera kategorin. Beroende på resultat ska API:et alltid returnera en statuskod tillbaka.
