### ISSUE TITLE
Api-Products: Som en administratör vill jag kunna redigera en kategori

### ISSUE THREAD

**Issue by codingbyahlv** [EC-rika-project/API-Products-RIKA-WIN23#8]
**Tasks:**

- [ ] Skapa API-endpoint för att uppdatera en kategori baserat på CategoryId
- [ ] Validera att kategorin existerar, samt att de nya indatan är giltig
- [ ] Implementera logik för att uppdatera kategorin i databasen
- [ ] Skriv enhetstester för att verifiera redigeringen av kategorin
- [ ] Implementera felhantering vid misslyckad uppdatering

**Definition of done:**
 
-  [ ] Administratören ska kunna redigera en kategori genom att ange kategorins ID och de fält som ska uppdateras.
- [ ] Systemet ska validera om kategori med det angivna ID:et existerar i databasen och så att alla obligatoriska fält är ifyllda. 
- [ ] API:et ska alltid returnera en statuskod beroende på resultatet.
Om valideringen lyckas, ska systemet uppdatera fälten som är redigerade.
